worker_processes auto;

events {
    worker_connections 1024;
}

http {
    log_format upstream '$remote_addr [$time_local] '
                        '"$request" $status '
                        'upstream=$upstream_addr '
                        'rt=$request_time upt=$upstream_response_time';

    access_log /var/log/nginx/access.log upstream;

    upstream api {
        server api-1:8080;
        server api-2:8080;
    }

    server {
        listen 9999;

        location / {
            proxy_pass http://api;
        }
    }
}
